### ISSUE TITLE
Search for users

### ISSUE THREAD

**Issue by SCKelemen** [wearehx/voting#11]
As a user, I would like to be able to search this page for people.
http://hackers-voting.herokuapp.com/data/users

**Comment by iangcarroll** [comment]
Ctrl+F makes this low priority; contributions from anyone welcome.

**Comment by SCKelemen** [comment]
I'll work on it after the holiday. I was just opening the issue for me. =)

**Comment by iangcarroll** [comment]
Any updates?

**Comment by SCKelemen** [comment]
=( sorry, haven't had time to look at it.

**Comment by iangcarroll** [comment]
Contributions welcome from anyone.

**Comment by SCKelemen** [comment]
I might work on this at MangoHacks.
