### ISSUE TITLE
Some votes do not have a UUID

### ISSUE THREAD

**Issue by iangcarroll** [wearehx/voting#30]
This is concerning. There are votes with a `null` UUID in `/data/votes`, which shouldn't be possible.

**Comment by iangcarroll** [comment]
There are 74 votes in the past two terms affected. The first term does not have this issue.

**Comment by SCKelemen** [comment]
O.o

**Comment by iangcarroll** [comment]
This was fixed in #31. We'll have to generate a UUID for those without one manually. // cc @gsingh93; ping me when you're available and I can write a one liner for this
