### ISSUE TITLE
Don't allow users to nominate the same person twice

### ISSUE THREAD

**Issue by gsingh93** [wearehx/voting#7]
I don't know if this is possible, but we should check if someone can use more than one of their nominations on a single person. If this is possible, we should prevent this, as that's not the point of nominations.

**Comment by iangcarroll** [comment]
I am fairly confident I wrote a check for this but I'll check.

**Comment by iangcarroll** [comment]
https://github.com/wearehx/voting/blob/master/app/Http/Controllers/NominationController.php#L43
